#! /bin/bash

set -e

stack build --copy-bins my-config:exe:xmobar
stack build my-config:exe:xmonad

xmonad_bin=$(stack exec which xmonad)

echo

if [ ! -z ${1+x} ]; then
    rm -f "$1"
    echo "Copying from ${xmonad_bin} to ${1}"
    cp "$xmonad_bin" "$1"
else
    echo "Bin is in ${xmonad_bin}; no copying performed"
fi

