#! /bin/bash

set -e

stack ghc -- \
    --make xmobar.hs \
    -i \
    -ilib \
    -fforce-recomp \
    -main-is main \
    -o xmobar

stack ghc -- \
    --make xmonad.hs \
    -i \
    -ilib \
    -fforce-recomp \
    -main-is main \
    -v0 \
    -o "$1"
