FROM dev-env-baseline

RUN apt-get install -y python3-pip python3-dev python3-venv
RUN apt-get install -y autoconf libssl-dev libxml2-dev libxslt1-dev libjpeg-dev \
    libffi-dev libudev-dev zlib1g-dev

CMD ["/usr/bin/zsh"]
